name: Deploy website

on:
  workflow_dispatch:

permissions: {}

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Build website
        run: |
          pnpm i --frozen-lockfile
          pnpm generate

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_URL }}
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWD }}
          local-dir: ./.output/public/
          server-dir: /